import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavMenu from "./components/NavMenu"; // ✅ import your NavMenu

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        {/* Navigation - appears on every page */}
        <NavMenu />

        {/* Page-specific content */}
        <main style={{ padding: "1rem" }}>{children}</main>
      </body>
    </html>
  );
}
